### ISSUE TITLE
Request: regular zip release

### ISSUE THREAD

**Issue by rubin55** [basharast/RetroArch-ARM#12]
I noticed that you package an appx now. I would much prefer a simple zip I can unpack, is it possible to make that available too (like it was in the past, I have a 1.10.x release from you which was packaged like that).

**Comment by jonshipman** [comment]
Install the .cer into your Trusted Root Certificate store (double click and choose install certificate) then double click the appx and install.

**Comment by FalconFour** [comment]
@jonshipman ~ This doesn't work. Installed certificate to "trusted root certificate authorities" (which no docs said to do, already having to browse here to find that tip), and the appx installer STILL tells me it refuses to allow installation:

`This app package’s publisher certificate could not be verified. Contact your system administrator or the app developer to obtain a new app package with verified certificates. The root certificate and all immediate certificates of the signature in the app package must be verified (0x800B010A)`

This is AFTER I fought with installing the "dependency" which told me it couldn't install because I needed to close some unknown Samsung applications (Galaxy Book Go - ARM64-based machine).

APPX downloads are a complete clusterf*k. Wish this could just be a simple ZIP/EXE app like everything else!

**Comment by rubin55** [comment]
@basharast: this issue is a request for a regular zip release; is it difficult to support this option? I would strongly prefer *not* to use appx, any certificate stuff, setting a machine to dev mode, or run a batch installer. Just a zip!

**Comment by basharast** [comment]
Hi @rubin55 , 
## What this repo for?
I'm working on `UWP` apps only and I hardly made [this release 1.10.x](https://github.com/basharast/RetroArch-ARM/releases/tag/1.10.2a) previously as exception to help some WindowsRT users.

** It's not the same development environment, totally different **

## Why I dropped the support for `zip` releases
Most features I made recently cannot be easily applied on that release `1.10.x` (tested only on `UWP`)
and they may not work at all

## Is it hard to do it?
I kept this issue opened because I want to help you when I got free time but my time is really very very limited, I can hardly work on UWP releases.

**Note:** if the `1.10.x` is working fine for you, then just use it.. not too much changes made other than `UWP` features.

Thanks for your understanding.

**Comment by basharast** [comment]
Close due to the reasons below:
- No WOA support/releases planned, Only UWP
- This is personal and not commercial repository

Suggested solutions:
- Find other repository that support WOA not UWP
- Ask in the official repository to add ARM support
- As mentioned in the home page:

   > I'm not affiliate with RetroArch or Libretro

I'm doing this fork for my self and other few users.

**Comment by jonshipman** [comment]
Above and beyond mate, appreciate the hard work you're doing. Works brilliantly on my Surface 2 and Surface Pro X (SQ1).
