### ISSUE TITLE
[ARM64] DInput support

### ISSUE THREAD

**Issue by rubin55** [basharast/RetroArch-ARM#3]
Hi, I'm using/testing/experimenting with your Windows-on-ARM64 RetroArch 1.10.2. I'm think I'm running into this issue upstream here (no mouse input detected: https://github.com/libretro/RetroArch/issues/11308). A workaround mentioned there is to use the `dinput` input driver, but it does not seem to be a part of your build (can't select it as an input driver).

**Comment by basharast** [comment]
Hi, thanks for reporting this issue.. I will check if it's possible to add it and inform you with any possible solution soon.

**Comment by basharast** [comment]
The development is going to be halted for long time due to some personal issues, 
I have been working for 3+ years on my own to provide some ARM solutions and that infected my own life a lot, 
and no plans to support ARM64
the main reasons in first place for this repo was ARM32 which is not compatible with dinput by default.
I hope the main repo will adopted official ARM support soon.
